baseurl = "https://stuartmccoll.github.io"
title = "Stuart McColl"
languageCode = "en"
theme = "hugo-theme-refresh"

pygmentsStyle = "github"
pygmentsUseClasses = true
pygmentsCodeFencers = true

[author]
  name = "Stuart McColl"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  enableEmoji = true
  description = "Stuart McColl software design and development blog"
  keywords = "homepage, blog, development, programming"
  images = [""]
  contentTypeName = "posts"

  title = "Stuart McColl"
  
  # Flag to toggle inclusion of license information
  includeLicense = true

  # Type of attribution license to use
  licenseType = "CC BY 4.0"

  # Link to attribution license
  licenseLink = "https://creativecommons.org/licenses/by/4.0"

  # Flag to toggle inclusion of GitHub issues link
  includeIssues = true

  # Link to create a new GitHub issue
  issuesLink = "https://github.com/stuartmccoll/hugo-theme-refresh/issues/new"

  # Flag to toggle inclusion of Twitter link
  includeMastodon = true

  # Twitter username
  mastodonUsername = "@stuartmccoll@hachyderm.io"

  # Flag to toggle inclusion of Hugo version details
  includeHugoVersion = true

  # Flag to toggle inclusion of Azure Application Insights
  includeApplicationInsights = true

  # Azure Application Insights connection string
  applicationInsightsConnectionString = "InstrumentationKey=74cc5c48-d066-4928-932e-459f438b579d;IngestionEndpoint=https://uksouth-1.in.applicationinsights.azure.com/;LiveEndpoint=https://uksouth.livediagnostics.monitor.azure.com/"

[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "github"
  tabWidth = 4
