name: Run WebsiteArchiver

on:
  push:
    branches:
      - main
      - feature/archival

jobs:
  archival:
    runs-on: ubuntu-latest
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: 'Deploy Azure Container Instance'
        uses: 'azure/aci-deploy@v1'
        with:
          cpu: 0.1
          dns-name-label: website-archiver
          environment-variables: AZURE_BLOB_STORAGE_CONTAINER_NAME=archives DOMAIN=https://stuartmccoll.github.io/
          image: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/websitearchiver:47594edaa5f3eebabb897401d0e90adac8146009
          location: 'uksouth'
          memory: 1
          name: websitearchiver
          secure-environment-variables: AZURE_BLOB_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}
          registry-login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          registry-password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
          resource-group: website-archiver
          restart-policy: Never
          
          
